apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qizt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-qizt@sha256:ed7d5c5f6a41a11dd0b93695be93251d8dcada31a7e4b59ef05c55c3bf58f682
        name: my-nodejs
        resources: {}
status: {}
